//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_Builder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C_Builder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Resources;
        ///using System.Reflection;
        ///using System.Diagnostics;
        ///
        ///namespace C_Builder
        ///{
        ///    static class Readandlaunch
        ///    {
        ///        static void Main()
        ///        {
        ///            try
        ///            {
        ///                string path = Path.GetTempPath() + &quot;//rec&quot;;
        ///                if (!Directory.Exists(path))
        ///                {
        ///                    Directory.CreateDirectory(path);
        ///                }
        ///                ResourceManager m = new ResourceManager(&quot;files&quot;, A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileToEXE {
            get {
                return ResourceManager.GetString("FileToEXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  System.IO.File.WriteAllBytes(path +&quot;{filname}&quot;, (byte[])m.GetObject(&quot;{ressources}&quot;));
        ///                System.Diagnostics.Process.Start(path + &quot;{filname}&quot;);.
        /// </summary>
        internal static string Possibility {
            get {
                return ResourceManager.GetString("Possibility", resourceCulture);
            }
        }
    }
}
